config/routes.rb
Rails.application.routes.draw do
  resources :hero_powers, only: [:create]
  resources :powers, only: [:index, :show, :update]
  resources :heroes, only: [:index, :show]
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/hero.rb
class Hero < ApplicationRecord
    has_many :hero_powers
    has_many :powers, through: :hero_powers
end

app/models/hero_power.rb
class HeroPower < ApplicationRecord
    belongs_to :hero 
    belongs_to :power

    validates :strength, inclusion: {in: ['Strong', 'Weak', 'Average']}
end

app/models/power.rb
class Power < ApplicationRecord
    has_many :hero_powers
    has_many :heroes, through: :hero_powers

    validates :description, length: { minimum: 20 }
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::API 
    
rescue_from ActiveRecord::RecordInvalid, with: :render_unprocessable_entity_response
    
    def render_unprocessable_entity_response(exception)
        render json: {errors: exception.record.errors.full_messages}, status: :unprocessable_entity
    end
end

app/controllers/hero_powers_controller.rb
class HeroPowersController < ApplicationController
  
  def create
    heropower = HeroPower.create!(hero_power_params)
    render json: heropower.hero, serializer:InvidualHeroSerializer
  end

  private

  def hero_power_params
    params.permit(:strength, :power_id, :hero_id)
  end
end

app/controllers/heroes_controller.rb
class HeroesController < ApplicationController

    def index 
        render json: Hero.all
    end

    def show 
        hero = Hero.find_by(id: params[:id])
        if hero
            render json: hero, serializer:InvidualHeroSerializer
        else
            render json: {error: "Hero not found"}, status: :not_found
        end        
    end
end

app/controllers/powers_controller.rb
class PowersController < ApplicationController
  
  def index 
    render json: Power.all
  end

  def show 
    power = Power.find_by(id: params[:id])
    if power
      render json: power
    else
      render json: {error: "Power not found"}, status: :not_found
    end
  end

  def update
    power = Power.find_by(id: params[:id])
    if power 
      power.update!(power_params)
      render json: power
    else
      render json: {error: "Power not found"}, status: :not_found
    end
  end

  private

  def power_params
    params.permit(:name, :description)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/hero_powers_helper.rb
module HeroPowersHelper
end

app/helpers/heroes_helper.rb
module HeroesHelper
end

app/helpers/heros_helper.rb
module HerosHelper
end

app/helpers/powers_helper.rb
module PowersHelper
end

app/views/hero_powers/_form.html.erb
<%= form_with(model: hero_power) do |form| %>
  <% if hero_power.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(hero_power.errors.count, "error") %> prohibited this hero_power from being saved:</h2>

      <ul>
        <% hero_power.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= form.label :strength, style: "display: block" %>
    <%= form.text_field :strength %>
  </div>

  <div>
    <%= form.label :hero_id, style: "display: block" %>
    <%= form.number_field :hero_id %>
  </div>

  <div>
    <%= form.label :power_id, style: "display: block" %>
    <%= form.number_field :power_id %>
  </div>

  <div>
    <%= form.submit %>
  </div>
<% end %>

app/views/hero_powers/_hero_power.html.erb
<div id="<%= dom_id hero_power %>">
  <p>
    <strong>Strength:</strong>
    <%= hero_power.strength %>
  </p>

  <p>
    <strong>Hero:</strong>
    <%= hero_power.hero_id %>
  </p>

  <p>
    <strong>Power:</strong>
    <%= hero_power.power_id %>
  </p>

</div>

app/views/hero_powers/edit.html.erb
<h1>Editing hero power</h1>

<%= render "form", hero_power: @hero_power %>

<br>

<div>
  <%= link_to "Show this hero power", @hero_power %> |
  <%= link_to "Back to hero powers", hero_powers_path %>
</div>

app/views/hero_powers/index.html.erb
<p style="color: green"><%= notice %></p>

<h1>Hero powers</h1>

<div id="hero_powers">
  <% @hero_powers.each do |hero_power| %>
    <%= render hero_power %>
    <p>
      <%= link_to "Show this hero power", hero_power %>
    </p>
  <% end %>
</div>

<%= link_to "New hero power", new_hero_power_path %>

app/views/hero_powers/new.html.erb
<h1>New hero power</h1>

<%= render "form", hero_power: @hero_power %>

<br>

<div>
  <%= link_to "Back to hero powers", hero_powers_path %>
</div>

app/views/hero_powers/show.html.erb
<p style="color: green"><%= notice %></p>

<%= render @hero_power %>

<div>
  <%= link_to "Edit this hero power", edit_hero_power_path(@hero_power) %> |
  <%= link_to "Back to hero powers", hero_powers_path %>

  <%= button_to "Destroy this hero power", @hero_power, method: :delete %>
</div>

app/views/heros/_form.html.erb
<%= form_with(model: hero) do |form| %>
  <% if hero.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(hero.errors.count, "error") %> prohibited this hero from being saved:</h2>

      <ul>
        <% hero.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= form.label :name, style: "display: block" %>
    <%= form.text_field :name %>
  </div>

  <div>
    <%= form.label :super_name, style: "display: block" %>
    <%= form.text_field :super_name %>
  </div>

  <div>
    <%= form.submit %>
  </div>
<% end %>

app/views/heros/_hero.html.erb
<div id="<%= dom_id hero %>">
  <p>
    <strong>Name:</strong>
    <%= hero.name %>
  </p>

  <p>
    <strong>Super name:</strong>
    <%= hero.super_name %>
  </p>

</div>

app/views/heros/edit.html.erb
<h1>Editing hero</h1>

<%= render "form", hero: @hero %>

<br>

<div>
  <%= link_to "Show this hero", @hero %> |
  <%= link_to "Back to heros", heros_path %>
</div>

app/views/heros/index.html.erb
<p style="color: green"><%= notice %></p>

<h1>Heros</h1>

<div id="heros">
  <% @heros.each do |hero| %>
    <%= render hero %>
    <p>
      <%= link_to "Show this hero", hero %>
    </p>
  <% end %>
</div>

<%= link_to "New hero", new_hero_path %>

app/views/heros/new.html.erb
<h1>New hero</h1>

<%= render "form", hero: @hero %>

<br>

<div>
  <%= link_to "Back to heros", heros_path %>
</div>

app/views/heros/show.html.erb
<p style="color: green"><%= notice %></p>

<%= render @hero %>

<div>
  <%= link_to "Edit this hero", edit_hero_path(@hero) %> |
  <%= link_to "Back to heros", heros_path %>

  <%= button_to "Destroy this hero", @hero, method: :delete %>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Superheroes</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application" %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/powers/_form.html.erb
<%= form_with(model: power) do |form| %>
  <% if power.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(power.errors.count, "error") %> prohibited this power from being saved:</h2>

      <ul>
        <% power.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= form.label :name, style: "display: block" %>
    <%= form.text_field :name %>
  </div>

  <div>
    <%= form.label :description, style: "display: block" %>
    <%= form.text_field :description %>
  </div>

  <div>
    <%= form.submit %>
  </div>
<% end %>

app/views/powers/_power.html.erb
<div id="<%= dom_id power %>">
  <p>
    <strong>Name:</strong>
    <%= power.name %>
  </p>

  <p>
    <strong>Description:</strong>
    <%= power.description %>
  </p>

</div>

app/views/powers/edit.html.erb
<h1>Editing power</h1>

<%= render "form", power: @power %>

<br>

<div>
  <%= link_to "Show this power", @power %> |
  <%= link_to "Back to powers", powers_path %>
</div>

app/views/powers/index.html.erb
<p style="color: green"><%= notice %></p>

<h1>Powers</h1>

<div id="powers">
  <% @powers.each do |power| %>
    <%= render power %>
    <p>
      <%= link_to "Show this power", power %>
    </p>
  <% end %>
</div>

<%= link_to "New power", new_power_path %>

app/views/powers/new.html.erb
<h1>New power</h1>

<%= render "form", power: @power %>

<br>

<div>
  <%= link_to "Back to powers", powers_path %>
</div>

app/views/powers/show.html.erb
<p style="color: green"><%= notice %></p>

<%= render @power %>

<div>
  <%= link_to "Edit this power", edit_power_path(@power) %> |
  <%= link_to "Back to powers", powers_path %>

  <%= button_to "Destroy this power", @power, method: :delete %>
</div>